const MANAGER_ROLES = ["BOSS", "PRODUCTION_MANAGER", "COORDINATOR"];

const PROJECT_STAGES = [
  "AUDIO",
  "ANIMATICS",
  "CHARACTER_MODELLING",
  "BLENDSHAPES",
  "BG_MODELLING",
  "RIGGING",
  "TEXTURING",
  "ANIMATION",
  "LIGHTING",
  "RENDER",
  "COMPOSITING",
  "EDITING"
];

const CHARACTER_STAGES = ["REFERENCE", "MODELLING", "BLENDSHAPES", "TEXTURING", "RIGGING"];

const ACTIVE_STAGE_STATUSES = ["NOT_STARTED", "IN_PROGRESS", "SUBMITTED", "REJECTED", "ISSUE", "EXTENDED"];

module.exports = {
  MANAGER_ROLES,
  PROJECT_STAGES,
  CHARACTER_STAGES,
  ACTIVE_STAGE_STATUSES
};
