export const STATUS_COLORS = {
  NOT_STARTED: "#6B7280",
  IN_PROGRESS: "#F59E0B",
  SUBMITTED: "#3B82F6",
  APPROVED: "#10B981",
  REJECTED: "#EF4444",
  REVISION_REQUIRED: "#DC2626",
  ISSUE: "#EF4444",
  EXTENDED: "#8B5CF6"
};

export const PROJECT_STAGES = [
  "AUDIO",
  "ANIMATICS",
  "MODELLING",
  "UNWRAPPING",
  "TEXTURING",
  "RIGGING",
  "ANIMATION",
  "FX",
  "LIGHTING",
  "COMPOSITING",
  "EDITING",
  // Legacy stage keys kept for existing records/routes.
  "CHARACTER_MODELLING",
  "BLENDSHAPES",
  "BG_MODELLING",
  "RENDER"
];

export const CHARACTER_STAGES = ["REFERENCE", "MODELLING", "BLENDSHAPES", "TEXTURING", "RIGGING"];

export const MANAGER_ROLES = ["BOSS", "PRODUCTION_MANAGER", "COORDINATOR"];

export const ISSUE_TYPES = [
  "TECHNICAL",
  "SOFTWARE_CRASH",
  "ASSET_MISSING",
  "HARDWARE_FAILURE",
  "ARTIST_UNAVAILABLE",
  "OTHER"
];

export const STAGE_STATUSES = [
  "NOT_STARTED",
  "IN_PROGRESS",
  "SUBMITTED",
  "APPROVED",
  "REJECTED",
  "REVISION_REQUIRED",
  "ISSUE",
  "EXTENDED"
];
